# 模块：项目/查询/站点配置/画像数据
# 默认站点配置 — 单一事实来源。
# 管理器/入口/均从此导入，不再各自手写。
# 阶段3.1:新增合并请求字典（21适配器完整画像）+字段


# ──适配器默认画像字典（阶段3.1路由评分器数据源）────────────────
# 键=适配器_，值=完整默认配置画像
# 字段说明：
# :中文显示名
# :行业关键词列表（用于行业匹配加分）
# _:标准号前缀列表（用于前缀精确匹配+30分）
# _:是否通用适配器（→-10降权）
# :可靠性评级（//）
# _:基础权重分
# _:速率限制子字典（_/_/_冷却/_）
# _:连续错误触发冷却阈值
# _:冷却持续秒数
# :路由角色（=主力站点,=后台补偿）

ADAPTER_DEFAULT_PROFILES: dict[str, dict] = {
    "std_gov": {
        "label": "全国标准信息公共服务平台",
        "industries": [],
        "std_prefixes": ["GB", "GB/T", "GB/Z"],
        "is_general": True,
        "reliability": "high",
        "default_weight": 70,
        "rate_limit": {"request_interval": 0.3, "batch_limit": 100, "batch_cooldown": 5},
        "cooling_threshold": 5,
        "cooling_duration": 30,
        "role": "primary",
    },
    "csres": {
        "label": "工标网",
        "industries": [],
        "std_prefixes": ["GB", "GB/T", "GB/Z"],
        "is_general": True,
        "reliability": "low",
        "default_weight": 30,
        "rate_limit": {"request_interval": 2.0, "batch_limit": 10, "batch_cooldown": 120},
        "cooling_threshold": 1,
        "cooling_duration": 86400,
        "role": "background",
    },
    "cssn": {
        "label": "中国标准服务网",
        "industries": [],
        "std_prefixes": ["GB", "GB/T"],
        "is_general": True,
        "reliability": "high",
        "default_weight": 60,
        "rate_limit": {"request_interval": 0.3, "batch_limit": 80, "batch_cooldown": 5},
        "cooling_threshold": 5,
        "cooling_duration": 30,
        "role": "primary",
    },
    "jjg": {
        "label": "国家计量技术规范全文公开系统",
        "industries": ["计量"],
        "std_prefixes": ["JJG", "JJF"],
        "is_general": False,
        "reliability": "high",
        "default_weight": 60,
        "rate_limit": {"request_interval": 0.3, "batch_limit": 80, "batch_cooldown": 5},
        "cooling_threshold": 5,
        "cooling_duration": 30,
        "role": "primary",
    },
    "ahbz": {
        "label": "安徽标准化信息服务平台",
        "industries": [],
        "std_prefixes": ["GB", "GB/T", "DB"],
        "is_general": True,
        "reliability": "high",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "hbba": {
        "label": "行业标准信息服务平台",
        "industries": [],
        "std_prefixes": ["SH", "NB", "HG", "JB", "YB", "SY", "CB", "QB", "FZ"],
        "is_general": False,
        "reliability": "high",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 900,
        "role": "primary",
    },
    "miit": {
        "label": "工信部行业标准查询",
        "industries": ["工业"],
        "std_prefixes": ["YD", "SJ"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "jtst": {
        "label": "交通运输部标准查询",
        "industries": ["交通"],
        "std_prefixes": ["JT", "JTG", "JTS"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "mee": {
        "label": "生态环境部标准查询",
        "industries": ["环保"],
        "std_prefixes": ["HJ", "GB"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "nrsis": {
        "label": "自然资源标准信息服务平台",
        "industries": ["自然资源"],
        "std_prefixes": ["DZ", "TD"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "sppt": {
        "label": "食品安全国家标准数据检索平台",
        "industries": ["食品"],
        "std_prefixes": ["GB"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "sppt_local": {
        "label": "食品安全地方标准数据检索平台",
        "industries": ["食品"],
        "std_prefixes": ["DB"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 50,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "tdpress": {
        "label": "铁路标准信息服务平台",
        "industries": ["铁路"],
        "std_prefixes": ["TB"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "ncha": {
        "label": "文物保护标准查询",
        "industries": ["文物"],
        "std_prefixes": ["WW"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "gongbiaoku": {
        "label": "工标库",
        "industries": [],
        "std_prefixes": [],
        "is_general": True,
        "reliability": "low",
        "default_weight": 40,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "energy": {
        "label": "能源标准信息服务平台",
        "industries": ["能源"],
        "std_prefixes": ["NB", "DL"],
        "is_general": False,
        "reliability": "low",
        "default_weight": 50,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "iso_gov": {
        "label": "ISO/IEC国际标准（全国标准平台子站）",
        "industries": [],
        "std_prefixes": ["ISO", "IEC", "IEEE"],
        "is_general": False,
        "reliability": "high",
        "default_weight": 60,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 600,
        "role": "primary",
    },
    "njbz365": {
        "label": "南京标准公共服务平台",
        "industries": [],
        "std_prefixes": [],
        "is_general": True,
        "reliability": "medium",
        "default_weight": 45,
        "rate_limit": {"request_interval": 3.0, "batch_limit": 20, "batch_cooldown": 30},
        "cooling_threshold": 3,
        "cooling_duration": 600,
        "role": "primary",
    },
    "ccsn": {
        "label": "中国工程建设标准化协会",
        "industries": ["工程建设"],
        "std_prefixes": ["CECS"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 50,
        "rate_limit": {"request_interval": 1.0, "batch_limit": 15, "batch_cooldown": 10},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
    "dbba": {
        "label": "地方标准信息服务平台",
        "industries": [],
        "std_prefixes": ["DB"],
        "is_general": False,
        "reliability": "high",
        "default_weight": 55,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 600,
        "role": "primary",
    },
    "ttbz": {
        "label": "全国团体标准信息平台",
        "industries": [],
        "std_prefixes": ["T/"],
        "is_general": False,
        "reliability": "medium",
        "default_weight": 50,
        "rate_limit": {"request_interval": 0.5, "batch_limit": 50, "batch_cooldown": 5},
        "cooling_threshold": 3,
        "cooling_duration": 300,
        "role": "primary",
    },
}
