# pilotstd/core/config/defaults.py
# 出厂默认值常量 — 从 config.py 拆分

import os

FACTORY_DEFAULTS = {
    "appearance.theme": "经典白",
    "appearance.language": "zh_CN",
    "appearance.column_visibility": [True] * 9,
    "appearance.icon_theme": "default",
    "appearance.skip_welcome": False,
    "appearance.hyphen_style": True,
    "storage.root_dir": os.path.expanduser("~/标准"),
    "storage.expire_folder": "过期作废",
    "storage.downloads_dir": None,
    "storage.inbox_dir": "/inbox",
    "storage.mirror_skipped_dirs": True,
    "storage.mirror_fallback": True,
    "organize.auto_clean_source": False,
    "network.proxy": "",
    "network.ua_rotation": True,
    "network.timeout": 30,
    "query.site_order": [],
    "query.use_cache": True,
    "query.use_announcement_match": False,
    "query.announcement_url": "http://localhost:9028",
    "query.announcement_api_key": "",
    "scan.skip_folders": [
        "过期作废",
        "征求意见稿",
        "培训课件",
        "建设项目过程资料及交工资料标准",
        "吊车性能",
        "标准图集",
    ],
    "scan.exclude_patterns": [
        "征求意见稿",
        "培训课件",
        "建设项目过程资料及交工资料标准",
        "吊车性能",
        "标准图集",
    ],
    "scan.extensions": [".pdf", ".doc", ".docx", ".txt"],
    "announcement.enabled": False,
    "ocr.provider": "",
    "ocr.baidu_api_key": "",
    "ocr.baidu_secret_key": "",
    "ocr.tencent_secret_id": "",
    "ocr.tencent_secret_key": "",
    "ocr.aliyun_access_key_id": "",
    "ocr.aliyun_access_key_secret": "",
    "file.clear_readonly": True,
    "watchdog.enabled": False,
    "notification.enabled": False,
    "notification.channels.wechat.enabled": True,
    "notification.channels.wechat.webhook_url": "",
    "notification.channels.telegram.enabled": False,
    "notification.channels.telegram.bot_token": "",
    "notification.channels.telegram.chat_id": "",
    "notification.channels.feishu.enabled": False,
    "notification.channels.feishu.webhook_url": "",
    "notification.rules.archive_complete": ["wechat"],
    "notification.rules.standard_status_changed": ["wechat"],
    "notification.rules.standard_expired": ["wechat"],
    "notification.rules.standard_first_registered": ["wechat"],
    "notification.rules.announcement_fetch_complete": ["wechat"],
    "notification.rules.auto_backup": ["wechat"],
    "notification.rules.announcement_check_complete": ["wechat"],
    "notification.rules.batch_download_complete": ["wechat"],
    "notification.rules.auto_scan_failed": ["wechat"],
    "notification.rules.validity_batch_report": ["wechat"],
    "notification.rules.validity_round_summary": ["wechat"],
    "notification.rules.validity_standard_failed": ["wechat"],
    "notification.rules.validity_system_failed": ["wechat"],
    "notification.rules.date_reminder": ["wechat"],
    # 通知日志清理
    "notification.log_retention_days": 30,
    "notification.log_cleanup_interval_hours": 24,
    # 服务端聚合（同类消息合并，防通知刷屏）
    "notification.aggregate_enabled": True,
    "notification.aggregate_window_seconds": 5,
    "notification.aggregate_max_events": 50,
    # aggregate_bypass_events 默认值由 events.BYPASS_EVENTS 派生，
    # 此处留空由 manager 层在读取时做回退，用户可通过 config.json 覆盖
    # 静音时段
    "notification.quiet_hours_enabled": False,
    "notification.quiet_hours_start": "22:00",
    "notification.quiet_hours_end": "07:00",
    "adapter.circuit_breaker.failure_threshold": 3,
    "adapter.circuit_breaker.freeze_durations": [30, 120, 360, 720],
    "adapter.circuit_breaker.reset_window_hours": 24,
    "validity.first_execution": None,
    "validity.total_weeks": 4,
    "validity.next_run": None,
    "validity.checked_count": 0,
    "validity.round_completed": False,
    "validity.batch_size": 50,
    "validity.batch_interval": 5,
    "validity.check_ratio": 25,
    "validity.frequency": "weekly",
    "validity.execute_time": "03:00",
    "validity.update_interval": 28,
    # ── Phase 4b: 日期提醒 ──
    "tasks.date_reminder_enabled": False,
    "tasks.date_reminder_cron": "0 2 * * *",
    "tasks.auto_archive_retry_enabled": True,
    "tasks.auto_archive_retry_cron": "0 4 * * *",
}
