#!/usr/bin/env python3
"""Bootstrap golden fixtures from live announcement URLs.

Usage:
    python scripts/bootstrap_golden.py          # download + parse + write
    python scripts/bootstrap_golden.py --verify # batch-set _verified=true
    pytest tests/golden/ -v                     # validate
"""

import json
from pathlib import Path

import requests

from pilotstd.announcement.parser import parse_announcement_detail

# Announcement detail page URLs (GB / HB / DB)
CASES = [
    ("001_gb_2026_31",
     "https://std.sacinfo.org.cn/gnoc/queryInfo?id=A183E1BFFEAAF0A1E9924E82AF7F0E5E"),
    ("002_hb_2026_07",
     "https://std.sacinfo.org.cn/gnocHb/queryInfo?id=32CD74B3B8C086AF1189179CBCAC44DFC12A3DED8ECF243688F82C29E3AF93ED"),
    ("003_db_2026_07",
     "https://std.sacinfo.org.cn/gnocDb/queryInfo?id=A539C7E6B264D72354D721405B9843CD5C8F24270DF5B898E02FEAC6E761C59C"),
]

FIXTURES_DIR = Path("tests/golden/fixtures")
EXPECTED_DIR = Path("tests/golden/expected")
FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
EXPECTED_DIR.mkdir(parents=True, exist_ok=True)

HEADERS = {"User-Agent": "Mozilla/5.0 (GoldenFixtureBot/1.0)"}

for name, url in CASES:
    print(f"downloading {name} ...")
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    html = resp.text
    (FIXTURES_DIR / f"{name}.html").write_text(html, encoding="utf-8")

    items, meta = parse_announcement_detail(html)
    result = {
        "_verified": False,
        "_source_url": url,
        "_notes": "auto-generated by bootstrap_golden.py. review and set _verified=true",
        "items": items,
        "meta": meta,
    }
    (EXPECTED_DIR / f"{name}.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    print(f"  -> {len(items)} items, meta title={meta.get('title', '')[:40]}")

print(f"\ndone. next: pytest tests/golden/ -v")
