#!/usr/bin/env python3
"""
G-032 文档生成器：capabilities_registry.md 能力矩阵自动更新。

数据源：
  - 代码库静态扫描（函数定义、关键模式、daemon 线程等）
  - 现有 capabilities_registry.md（保留人工编写的描述列）

输出：
  - docs/governance/capabilities_registry.md（含 AUTO-GENERATED 标记）

降级策略：
  - 源文件不存在 → 跳过对应条目，输出警告，exit 0
  - 无法解析 registry → 生成最小空矩阵，exit 0
"""
import ast
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Windows 控制台 UTF-8 编码兼容
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_FILE = PROJECT_ROOT / "docs" / "governance" / "capabilities_registry.md"

TIMESTAMP = datetime.now(timezone.utc).isoformat()
AUTO_HEADER = f"<!-- AUTO-GENERATED by scripts/generate_capabilities.py at {TIMESTAMP} -->"
DO_NOT_EDIT = "<!-- DO NOT EDIT MANUALLY. Lines above this marker are auto-maintained. -->"

# ─── 追踪规则：自动扫描的代码模式 ───
# 每条规则: {file, pattern, kind, label}
# kind: 'func' → AST 查找函数定义行号
# kind: 'regex' → 正则扫描行号
# kind: 'class' → AST 查找类定义行号

TRACK_RULES: list[dict] = [
    # docker/scheduler.py
    {"file": "docker/scheduler.py", "pattern": r"scheduler\s*=\s*BackgroundScheduler", "kind": "regex", "label": "调度器实例"},
    {"file": "docker/scheduler.py", "pattern": r"_heartbeat_loop", "kind": "func", "label": "调度器心跳循环"},
    {"file": "docker/scheduler.py", "pattern": r"_acquire_scheduler_lock", "kind": "func", "label": "调度器互斥锁"},
    {"file": "docker/scheduler.py", "pattern": r"stop_scheduler", "kind": "func", "label": "调度器优雅关闭"},
    # docker/app.py
    {"file": "docker/app.py", "pattern": r"lifespan", "kind": "func", "label": "FastAPI 生命周期"},
    # query/engine.py
    {"file": "pilotstd/query/engine.py", "pattern": r"_progress_heartbeat", "kind": "func", "label": "引擎进度心跳"},
    {"file": "pilotstd/query/engine.py", "pattern": r"ThreadPoolExecutor", "kind": "regex", "label": "引擎线程池"},
    # query/rotator.py
    {"file": "pilotstd/query/rotator.py", "pattern": r"cooldown|_enter_cooldown", "kind": "regex", "label": "轮转器冷却"},
    # scan/watcher.py
    {"file": "pilotstd/scan/watcher.py", "pattern": r"Observer|watchdog", "kind": "regex", "label": "文件监控"},
    # download/engine.py
    {"file": "pilotstd/download/engine.py", "pattern": r"ThreadPoolExecutor|_download", "kind": "regex", "label": "下载线程池"},
    # announcement
    {"file": "pilotstd/announcement/base.py", "pattern": r"_MAX_DETAIL_WORKERS|ThreadPoolExecutor", "kind": "regex", "label": "公告基础并行"},
    {"file": "pilotstd/announcement/monitor.py", "pattern": r"elapsed|_track", "kind": "regex", "label": "公告阶段耗时"},
    # core
    {"file": "pilotstd/core/file_index.py", "pattern": r"_cleanup|daemon", "kind": "regex", "label": "文件索引清理线程"},
    {"file": "pilotstd/core/logger.py", "pattern": r"LoggerManager", "kind": "class", "label": "LoggerManager"},
    {"file": "pilotstd/core/updater.py", "pattern": r"download.*update|_verify", "kind": "regex", "label": "软件自更新"},
    # manager
    {"file": "pilotstd/manager/scheduled_service.py", "pattern": r"ScheduledService", "kind": "class", "label": "定时任务编排"},
    # docker/auth.py
    {"file": "docker/auth.py", "pattern": r"create_access_token|verify.*token", "kind": "func", "label": "JWT + API Key"},
]


def find_line_in_file(filepath: Path, pattern: str, kind: str) -> int | None:
    """在文件中查找模式所在行号。"""
    if not filepath.exists():
        return None
    try:
        if kind == "regex":
            content = filepath.read_text(encoding="utf-8")
            for i, line in enumerate(content.split("\n"), 1):
                if re.search(pattern, line):
                    return i
        elif kind == "func":
            tree = ast.parse(filepath.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if re.search(pattern, node.name):
                        return node.lineno
        elif kind == "class":
            tree = ast.parse(filepath.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    if re.search(pattern, node.name):
                        return node.lineno
    except (SyntaxError, UnicodeDecodeError, FileNotFoundError) as e:
        print(f"   ⚠️  解析 {filepath} 失败: {e}")
    return None


def scan_capabilities() -> list[dict]:
    """扫描代码库，返回能力列表。"""
    results = []
    for rule in TRACK_RULES:
        fp = PROJECT_ROOT / rule["file"]
        lineno = find_line_in_file(fp, rule["pattern"], rule["kind"])
        status = "active" if lineno is not None else "missing"
        results.append({
            "label": rule["label"],
            "file": rule["file"],
            "lineno": f"L{lineno}" if lineno else "—",
            "status": status,
            "pattern": rule["pattern"],
        })
        if lineno is None:
            print(f"   ⚠️  未找到: {rule['label']} ({rule['file']})")
    return results


def read_existing_descriptions() -> dict[str, str]:
    """从现有 registry 中读取人工编写的描述列。"""
    descriptions = {}
    if not REGISTRY_FILE.exists():
        return descriptions

    content = REGISTRY_FILE.read_text(encoding="utf-8")
    in_table = False
    for line in content.split("\n"):
        if line.startswith("| 功能模块"):
            in_table = True
            continue
        if in_table and line.startswith("|") and not line.startswith("|---"):
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 7:
                label = parts[1]
                desc = parts[6] if len(parts) > 6 else ""
                descriptions[label] = desc
        elif in_table and not line.startswith("|"):
            break
    return descriptions


def generate_registry(capabilities: list[dict]) -> str:
    """生成完整的 capabilities_registry.md 内容。"""
    descriptions = read_existing_descriptions()

    # 构建表格
    rows = []
    for cap in capabilities:
        desc = descriptions.get(cap["label"], "")
        rows.append(
            f"| {cap['label']} | `{cap['file']}` | `{cap['pattern'][:40]}` "
            f"| {cap['lineno']} | {cap['status']} | {desc} |"
        )

    table_header = "| 功能模块 | 文件路径 | 标识符/关键点 | 行号 | 状态 | 描述 |"
    table_sep = "|---------|---------|-------------|------|------|------|"

    return f"""{AUTO_HEADER}
{DO_NOT_EDIT}

# 能力登记簿（自动生成）

> PilotStd 项目非功能性能力清单。
> 生成时间：{TIMESTAMP}
> 数据来源：代码库静态扫描

## 能力登记表

{table_header}
{table_sep}
{chr(10).join(rows)}

## 统计

| 指标 | 数值 |
|------|------|
| 能力总数 | {len(capabilities)} |
| 活跃 | {sum(1 for c in capabilities if c['status'] == 'active')} |
| 缺失 | {sum(1 for c in capabilities if c['status'] == 'missing')} |

## 说明

- 行号由 AST 解析 + 正则扫描自动获取，每次 `check_all.sh --docs` 时刷新
- "状态" 列：active=源代码中存在，missing=未找到（可能已删除或重构）
- 描述列出人工维护，如需修改请在本文档中编辑（生成器不会覆盖描述列）
- 新增能力请在 TRACK_RULES 中添加追踪规则
"""


def main():
    """扫描代码库生成能力矩阵，写入 capabilities_registry.md。"""
    print("📊 generate_capabilities.py 开始执行...")

    if not REGISTRY_FILE.exists():
        print("   ⚠️  capabilities_registry.md 不存在，将创建新文件")

    capabilities = scan_capabilities()
    print(f"   扫描完成: {len(capabilities)} 项能力")

    content = generate_registry(capabilities)
    REGISTRY_FILE.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_FILE.write_text(content, encoding="utf-8")
    print(f"   ✅ capabilities_registry.md 已更新")


if __name__ == "__main__":
    main()
