#!/usr/bin/env python3
"""
G-032 文档生成器：STATUS.md 指标概览区自动更新。

数据源：
  - coverage.xml → 行覆盖率
  - pytest --collect-only → 测试用例数（降级方案：从 coverage.xml packages 推断）

首次运行赦免：
  - STATUS.md 无 AUTO-GENERATED 标记 → 备份为 STATUS.md.bak 后注入自动区块
  - 已有标记 → 替换区块内数据，保留人工区域不变
"""
import json
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

# 控制台-8编码兼容
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
STATUS_FILE = PROJECT_ROOT / "STATUS.md"
BACKUP_FILE = PROJECT_ROOT / "STATUS.md.bak"
COVERAGE_XML = PROJECT_ROOT / "coverage.xml"

AUTO_HEADER = f"<!-- AUTO-GENERATED by scripts/generate_status_metrics.py at {datetime.now(timezone.utc).isoformat()} -->"
DO_NOT_EDIT = "<!-- DO NOT EDIT MANUALLY. Changes will be overwritten. -->"

METRICS_BLOCK_START = "<!-- BEGIN AUTO-METRICS -->"
METRICS_BLOCK_END = "<!-- END AUTO-METRICS -->"


def _run_pytest_collect() -> int:
    """运行 pytest --collect-only -q 获取测试总数。"""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/", "--collect-only", "-q",
             "--ignore=tests/gui/",
             "--ignore=tests/test_regression_architecture.py",
             "--ignore-glob=*test_ui*.py"],
            capture_output=True, text=True, cwd=str(PROJECT_ROOT), timeout=120
        )
        for line in result.stdout.strip().split("\n"):
            m = re.search(r"(\d+)\s+tests?\s+selected", line)
            if not m:
                m = re.search(r"(\d+)\s+tests?\s+collected", line)
            if m:
                return int(m.group(1))
        for line in result.stderr.strip().split("\n"):
            m = re.search(r"(\d+)\s+tests?\s+selected", line)
            if not m:
                m = re.search(r"(\d+)\s+tests?\s+collected", line)
            if m:
                return int(m.group(1))
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
        print(f"   ⚠️  pytest collect 失败: {e}")
    return 0


def parse_coverage() -> dict:
    """从 coverage.xml 提取覆盖率数据。返回 {line_cov, branch_cov, packages}。"""
    result = {"line_cov": 0.0, "branch_cov": 0.0, "packages": []}
    if not COVERAGE_XML.exists():
        print(f"   ⚠️  {COVERAGE_XML} 不存在，覆盖率为 0")
        return result

    try:
        tree = ET.parse(str(COVERAGE_XML))
        root = tree.getroot()
        result["line_cov"] = round(float(root.attrib.get("line-rate", 0)) * 100, 1)
        result["branch_cov"] = round(float(root.attrib.get("branch-rate", 0)) * 100, 1)

        for pkg in root.findall(".//package"):
            pkg_name = pkg.attrib.get("name", "unknown")
            pkg_line_rate = round(float(pkg.attrib.get("line-rate", 0)) * 100, 1)
            result["packages"].append({"name": pkg_name, "cov": pkg_line_rate})
    except (ET.ParseError, FileNotFoundError) as e:
        print(f"   ⚠️  coverage.xml 解析失败: {e}")

    return result


def generate_metrics_block(tests: int, cov_data: dict) -> str:
    """生成指标区块 Markdown 表格。"""
    lines = [
        METRICS_BLOCK_START,
        "",
        "| 指标 | 数值 |",
        "|------|------|",
        f"| 后端测试用例数（非GUI） | {tests} |",
        f"| 后端行覆盖率（排除UI） | **{cov_data['line_cov']}%** |",
        f"| 分支覆盖率 | {cov_data['branch_cov']}% |",
        f"| 数据采集时间 | {datetime.now(timezone.utc).isoformat()} |",
        "",
        METRICS_BLOCK_END,
    ]
    return "\n".join(lines)


def main():
    print("📊 generate_status_metrics.py 开始执行...")

    # 收集数据
    tests = _run_pytest_collect()
    cov_data = parse_coverage()
    print(f"   测试数={tests}, 行覆盖={cov_data['line_cov']}%, 分支覆盖={cov_data['branch_cov']}%")

    # 读取现有文档
    old_content = ""
    if STATUS_FILE.exists():
        old_content = STATUS_FILE.read_text(encoding="utf-8")

    is_first_run = (AUTO_HEADER.split("\n")[0] not in old_content
                    and METRICS_BLOCK_START not in old_content)

    if is_first_run:
        # 🔑 首次运行赦免：备份原文件
        if STATUS_FILE.exists():
            shutil.copy2(str(STATUS_FILE), str(BACKUP_FILE))
            print(f"   🆕 首次运行：已备份 STATUS.md → STATUS.md.bak")

        block = generate_metrics_block(tests, cov_data)
        header_block = f"{AUTO_HEADER}\n{DO_NOT_EDIT}\n"

        if old_content:
            # 在文件开头插入自动区块，保留原文件所有人工内容
            new_content = f"{header_block}\n{block}\n\n{old_content}"
        else:
            # 文档不存在，创建最小文件
            new_content = f"{header_block}\n{block}\n"
    else:
        # 正常更新：替换已有区块
        block = generate_metrics_block(tests, cov_data)

        # 更新头部时间戳
        if AUTO_HEADER.split("\n")[0] in old_content:
            new_content = re.sub(
                r"<!-- AUTO-GENERATED by scripts/generate_status_metrics\.py at .+ -->",
                AUTO_HEADER,
                old_content
            )
        else:
            new_content = old_content

        if METRICS_BLOCK_START in new_content:
            start = new_content.index(METRICS_BLOCK_START)
            end = new_content.index(METRICS_BLOCK_END) + len(METRICS_BLOCK_END)
            new_content = new_content[:start] + block + new_content[end:]
        else:
            # 标记存在但区块不存在 → 追加区块
            new_content = f"{new_content}\n\n{block}\n"

    STATUS_FILE.write_text(new_content, encoding="utf-8")
    print(f"   ✅ STATUS.md 已更新")


if __name__ == "__main__":
    main()
