#!/usr/bin/env python3
"""
G-032 文档生成器：docs/testing/coverage-report.md 全文自动生成。

数据源：coverage.xml（由 pytest --cov --cov-report=xml 生成）
输出：docs/testing/coverage-report.md（完全覆盖，不含人工编辑区）
"""
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

# 控制台-8编码兼容
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = PROJECT_ROOT / "docs" / "testing" / "coverage-report.md"
COVERAGE_XML = PROJECT_ROOT / "coverage.xml"

TIMESTAMP = datetime.now(timezone.utc).isoformat()

# 模块中文名称映射
MODULE_NAMES = {
    "pilotstd.models": "数据模型",
    "pilotstd.quality": "代码质量检查",
    "pilotstd.__init__": "包初始化",
    "pilotstd.cli": "CLI 命令行",
    "pilotstd.i18n": "国际化",
    "pilotstd.task": "任务调度",
    "pilotstd.scan": "文件扫描",
    "pilotstd.download": "下载模块",
    "pilotstd.query": "查询引擎",
    "pilotstd.pipeline": "管线处理",
    "pilotstd.platform": "平台通知",
    "pilotstd.core": "核心模块",
    "pilotstd.organizer": "文件组织",
    "pilotstd.announcement": "公告处理",
    "pilotstd.manager": "管理器",
    "pilotstd.tasks": "异步任务",
    "pilotstd.monitor": "文件监控",
    "pilotstd.ui": "GUI 界面",
    "pilotstd.wechat_ip": "企业微信 IP",
}


def parse_coverage_xml() -> dict:
    """解析 coverage.xml，返回按模块分组的覆盖率数据。"""
    result = {"total_line_cov": 0.0, "total_branch_cov": 0.0, "modules": []}

    if not COVERAGE_XML.exists():
        return result

    try:
        tree = ET.parse(str(COVERAGE_XML))
        root = tree.getroot()
        result["total_line_cov"] = round(float(root.attrib.get("line-rate", 0)) * 100, 1)
        result["total_branch_cov"] = round(float(root.attrib.get("branch-rate", 0)) * 100, 1)

        for pkg in root.findall(".//package"):
            name = pkg.attrib.get("name", "unknown")
            line_rate = float(pkg.attrib.get("line-rate", 0))
            branch_rate = float(pkg.attrib.get("branch-rate", 0))
            stmts = int(float(pkg.attrib.get("statements", pkg.attrib.get("lines-valid", 0))))
            # 获取缺失行数
            missing_lines = 0
            for cls_elem in pkg.findall(".//class"):
                for line_elem in cls_elem.findall(".//line"):
                    if line_elem.attrib.get("hits", "1") == "0":
                        missing_lines += 1

            result["modules"].append({
                "name": name,
                "label": MODULE_NAMES.get(name, name),
                "line_cov": round(line_rate * 100, 1),
                "branch_cov": round(branch_rate * 100, 1),
                "stmts": stmts,
                "missing": missing_lines,
            })

        # 按覆盖率升序排列
        result["modules"].sort(key=lambda x: x["line_cov"])
    except (ET.ParseError, FileNotFoundError, ValueError) as e:
        print(f"   ⚠️  coverage.xml 解析失败: {e}")

    return result


def main():
    print("📊 generate_coverage_report.py 开始执行...")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    data = parse_coverage_xml()

    if not data["modules"]:
        print("   ⚠️  无覆盖率数据，生成空报告")
        cov_table = "| — | — | — |\n| 无数据 | — | — |\n"
        total_line = 0.0
        total_branch = 0.0
    else:
        total_line = data["total_line_cov"]
        total_branch = data["total_branch_cov"]

        # 构建模块表格
        rows = []
        for m in data["modules"]:
            status = "✅" if m["line_cov"] >= 80 else ("⚠️" if m["line_cov"] >= 50 else "❌")
            rows.append(
                f"| {m['label']} (`{m['name']}`) | {m['line_cov']}% | {m['branch_cov']}% "
                f"| {m['stmts']} | {m['missing']} | {status} |"
            )

        cov_table = "\n".join([
            "| 模块 | 行覆盖率 | 分支覆盖率 | 语句数 | 缺失行 | 状态 |",
            "|------|---------|-----------|--------|--------|:--:|",
        ] + rows)

    content = f"""<!-- AUTO-GENERATED by scripts/generate_coverage_report.py at {TIMESTAMP} -->
<!-- DO NOT EDIT MANUALLY. Changes will be overwritten. -->

# 覆盖率报告

> **生成时间**：{TIMESTAMP}
> **数据来源**：`coverage.xml`（`pytest --cov=pilotstd --cov-report=xml`）

## 整体覆盖率

| 指标 | 数值 |
|------|------|
| 行覆盖率 | **{total_line}%** |
| 分支覆盖率 | {total_branch}% |

## 各模块覆盖率

{cov_table}

## 门禁状态

| 门禁 | 阈值 | 当前值 | 状态 |
|------|------|--------|:--:|
| G-034 覆盖率阈值 | ≥ 80% | {total_line}% | {"✅ 通过" if total_line >= 80 else "❌ 未达标"} |
| CI test-backend | ≥ 45% | {total_line}% | {"✅ 通过" if total_line >= 45 else "❌ 未达标"} |

## 说明

- 本报告由 CI 自动生成，每次 `check_all.sh --docs` 运行时覆盖
- `pilotstd/ui/` 在 headless 环境下覆盖率为 0%，实际由 Windows CI `test-unit-cov` job 单独收集
- 如需手动补充分析，请在仓库外维护独立文档
"""
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"   ✅ coverage-report.md 已生成（{len(data['modules'])} 个模块）")


if __name__ == "__main__":
    main()
